<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-UDJ5PR4" name="test" tests="5" failures="2" timestamp="17 Dec 2019 08:30:57 GMT" time="0.026" errors="0">
  <testcase name="test1" time="0.008" classname="test.Demo1">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
	at test.Demo1.test1(Unknown Source)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.0" classname="test.Demo1">
    <failure type="java.lang.AssertionError" message="expected [4] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [4] but found [1]
	at test.Demo1.test2(Unknown Source)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test3" time="0.001" classname="test.Demo1"/>
  <testcase name="test4" time="0.0" classname="test.Demo1"/>
  <testcase name="test5" time="0.0" classname="test.Demo1"/>
</testsuite> <!-- test -->
