<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-UDJ5PR4" name="test" tests="3" failures="2" timestamp="12 Nov 2019 04:55:32 GMT" time="0.042" errors="0">
  <testcase name="test1" time="0.015" classname="practice.Demo1">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
	at practice.Demo1.test1(Demo1.java:11)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.001" classname="practice.Demo1">
    <failure type="java.lang.AssertionError" message="expected [4] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [4] but found [1]
	at practice.Demo1.test2(Demo1.java:17)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test3" time="0.0" classname="practice.Demo1"/>
</testsuite> <!-- test -->
